name: Extract IPs from URL

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Runs daily at midnight (adjust as needed)

jobs:
  extract-ips:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download the source file
      - name: Download source file
        run: curl -s -o trackers_all_ip.txt https://raw.githubusercontent.com/ngosang/trackerslist/refs/heads/master/trackers_all_ip.txt

      # Extract only the IPs
      - name: Extract IP addresses
        run: |
          grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' trackers_all_ip.txt > extracted_ips.txt
          echo "Extracted IPs:"
          cat extracted_ips.txt

      # Commit and push the extracted IPs file
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add extracted_ips.txt
          git commit -m "Update extracted IPs"
          git push
